#!/usr/bin/env python3

import roslaunch
import rospy

from topological_map_ros.topological_map_server import TopologicalMapServer

if __name__ == "__main__":
    rospy.init_node("topological_map_server")

    topo_map = TopologicalMapServer()
    rospy.spin()
